### ISSUE TITLE
[DBAAS-6] Разобраться, какие сущности нужно создать в kubernetes, чтобы поднять в нем приложение

### ISSUE THREAD

**Issue by cloud-core-team** [cloud-core-team/dbaas#6]
Результат: текстовый файл с описанием

**Comment by SobolevD** [comment]
Для добавления приложения в kubernetes должен быть Deployment.yaml файл. Этот файл должен находиться в репозитории.
Например, в папке deployments/templates.

Примерное содержимое деплоймента (yaml):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbaas
spec:
  selector:
    matchLabels:
      app: dbaas
  replicas: 1
  template:
    metadata:
      labels:
        app: dbaas
    spec:
      containers:
        - name: dbaas
          image: pseudo/your-image:latest
        ports:
        - containerPort: 8080
```

Для взаимодействия с приложением нам будет необходим ингресс и сервис.
Сервис позволяет общаться с подой. Но у сервиса нет внешнего URL, только внутренний. 
А задача ингресса - создать внешний URL и привязать его к внутреннему.

Примерное содержимое сервиса (yaml):

```yaml
apiVersion: v1
kind: Service
metadata:
  name: dbaas
spec:
  selector:
    app.kubernetes.io/name: dbaas
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
```

Примерное содержимое ингресса (yaml):

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbaas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: dbaas
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dbaas
            port:
              number: 8080
```
